# Generated by Django 4.2.11 on 2024-04-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_approach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candle",
            name="encoding_type",
            field=models.CharField(
                choices=[("JSON", "json")], db_index=True, default="JSON", max_length=50
            ),
            preserve_default=False,
        ),
    ]
